/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.HeadlessException;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import services.ConnectionProvider;

/**
 *
 * @author hi
 */
public class LostBook extends javax.swing.JFrame {

    Statement stmt;
    Connection con;

    public LostBook() {
        initComponents();
        dateToday();
        currentDate.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        studIDField = new javax.swing.JTextField();
        bookIDField = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lostBtn = new javax.swing.JButton();
        studIDField1 = new javax.swing.JTextField();
        currentDate = new com.toedter.calendar.JDateChooser();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(null);

        studIDField.setBackground(new java.awt.Color(244, 243, 234));
        studIDField.setBorder(null);
        jPanel1.add(studIDField);
        studIDField.setBounds(130, 150, 200, 30);

        bookIDField.setBackground(new java.awt.Color(244, 243, 234));
        bookIDField.setBorder(null);
        jPanel1.add(bookIDField);
        bookIDField.setBounds(130, 90, 200, 30);

        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Student ID :");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(20, 150, 102, 25);

        jLabel2.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Manage Lost Book");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(80, 30, 220, 32);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Book ID     :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(20, 90, 110, 25);

        lostBtn.setText("ADD");
        lostBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lostBtnActionPerformed(evt);
            }
        });
        jPanel1.add(lostBtn);
        lostBtn.setBounds(220, 230, 73, 23);

        studIDField1.setBackground(new java.awt.Color(244, 243, 234));
        studIDField1.setBorder(null);
        jPanel1.add(studIDField1);
        studIDField1.setBounds(130, 150, 200, 30);
        jPanel1.add(currentDate);
        currentDate.setBounds(130, 190, 200, 30);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 360, 320));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lostBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lostBtnActionPerformed
        int bookID = Integer.parseInt(bookIDField.getText());
        int studentID = Integer.parseInt(studIDField.getText());
        SimpleDateFormat dateFormat = new SimpleDateFormat("yyyy-MM-dd");
        String dob = "" + currentDate.getDate();
        String today = dateFormat.format(currentDate.getDate());

        try {
            con = ConnectionProvider.getCon();
            stmt = con.createStatement();
            stmt.executeUpdate("INSERT INTO lostbooks(bookID,studentID,reportedAt) VALUES('" + bookID + "','" + studentID + "', '" + today + "')");
            
            String query = String.format("UPDATE books SET noOfCopies = ((SELECT noOfCopies FROM books WHERE bookID = %d) -1) WHERE bookID = %d",bookID,bookID);
            stmt.executeUpdate(query);
             JOptionPane.showConfirmDialog(null, "Are you sure you want to add this to the lost books?");
            String sql = String.format("SELECT price FROM `books` WHERE bookID=%d", bookID);
            stmt.executeQuery(sql);
            String price = ("Book Price to be paid is: "+sql);
            JOptionPane.showMessageDialog(null,price);
          
            setVisible(false);
            new LostBook().setVisible(true);

        } catch (Exception err) {
            JOptionPane.showMessageDialog(null, err);
//            setVisible(false);
//            new LostBook().setVisible(true);
        } finally {
            try {
                stmt.close();
                con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_lostBtnActionPerformed

    private void dateToday() {
        long millis = System.currentTimeMillis();
        java.sql.Date date = new java.sql.Date(millis);
        currentDate.setDate(date);
        currentDate.setEnabled(false);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LostBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LostBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LostBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LostBook.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LostBook().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField bookIDField;
    private com.toedter.calendar.JDateChooser currentDate;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton lostBtn;
    private javax.swing.JTextField studIDField;
    private javax.swing.JTextField studIDField1;
    // End of variables declaration//GEN-END:variables
}
