/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import java.awt.HeadlessException;
import java.sql.*;
import services.ConnectionProvider;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import net.proteanit.sql.DbUtils;
import javax.swing.border.Border;

/**
 *
 * @author hi
 */
public class Student extends javax.swing.JFrame {

    public Connection con = null;
    public Statement stmt = null;

    public Student() {
        initComponents();
        fetch_data();
    }
    //to get the data from the database and display on the table

    public void fetch_data() {
        DefaultTableModel dm;
        dm = (DefaultTableModel) studentList.getModel();

        try {
            con = ConnectionProvider.getCon();
            stmt = con.createStatement();
            String sql = "select * from student";
            ResultSet rs = stmt.executeQuery(sql);
            studentList.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (Exception e) {
            System.out.println(e);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        firstNameField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lastNameField = new javax.swing.JTextField();
        courseCombo = new javax.swing.JComboBox<>();
        studentIDField = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        branchCombo = new javax.swing.JComboBox<>();
        addBtn = new javax.swing.JButton();
        cancel = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        deleteBtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        studentList = new rojerusan.RSTableMetro();
        jPanel4 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));
        setLocation(new java.awt.Point(270, 70));
        setMinimumSize(new java.awt.Dimension(1095, 710));
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(233, 246, 250));
        jPanel1.setMaximumSize(new java.awt.Dimension(1095, 710));
        jPanel1.setMinimumSize(new java.awt.Dimension(1095, 710));
        jPanel1.setPreferredSize(new java.awt.Dimension(1095, 710));
        jPanel1.setLayout(null);

        firstNameField.setBackground(new java.awt.Color(233, 246, 250));
        firstNameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        firstNameField.setBorder(null);
        firstNameField.setPreferredSize(new java.awt.Dimension(200, 20));
        firstNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                firstNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(firstNameField);
        firstNameField.setBounds(510, 160, 270, 40);

        jLabel7.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel7.setText("First Name      :");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(340, 170, 134, 25);

        jLabel3.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel3.setText("Last Name      :");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(340, 230, 131, 25);

        lastNameField.setBackground(new java.awt.Color(233, 246, 250));
        lastNameField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lastNameField.setBorder(null);
        lastNameField.setPreferredSize(new java.awt.Dimension(200, 20));
        lastNameField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lastNameFieldActionPerformed(evt);
            }
        });
        jPanel1.add(lastNameField);
        lastNameField.setBounds(510, 220, 270, 40);

        courseCombo.setBackground(new java.awt.Color(255, 255, 204));
        courseCombo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        courseCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Formal Sciences", "Natural Sciences", "Education", "Engineering", "Business", "Social Science" }));
        courseCombo.setBorder(null);
        courseCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                courseComboActionPerformed(evt);
            }
        });
        jPanel1.add(courseCombo);
        courseCombo.setBounds(490, 280, 270, 40);

        studentIDField.setBackground(new java.awt.Color(233, 246, 250));
        studentIDField.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        studentIDField.setBorder(null);
        studentIDField.setPreferredSize(new java.awt.Dimension(200, 20));
        studentIDField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                studentIDFieldActionPerformed(evt);
            }
        });
        jPanel1.add(studentIDField);
        studentIDField.setBounds(510, 100, 270, 40);

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel4.setText("Course Name :");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(340, 290, 126, 25);

        jLabel5.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel5.setText("Branch Name :");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(340, 340, 126, 25);

        branchCombo.setBackground(new java.awt.Color(255, 255, 204));
        branchCombo.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        branchCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "BSIT", "BSCS", "BSIS", "BS Mathematics", "BSBA", "BSA", "BSED", "BSChe", "BSES" }));
        branchCombo.setBorder(null);
        jPanel1.add(branchCombo);
        branchCombo.setBounds(490, 340, 270, 40);

        addBtn.setBackground(new java.awt.Color(0, 0, 0));
        addBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/add.png"))); // NOI18N
        addBtn.setText("ADD");
        addBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));
        addBtn.setContentAreaFilled(false);
        addBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addBtnActionPerformed(evt);
            }
        });
        jPanel1.add(addBtn);
        addBtn.setBounds(350, 410, 120, 40);

        cancel.setBackground(new java.awt.Color(153, 255, 153));
        cancel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cancel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red-x-mark-transparent-background-3.png"))); // NOI18N
        cancel.setText("Cancel");
        cancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelActionPerformed(evt);
            }
        });
        jPanel1.add(cancel);
        cancel.setBounds(910, 50, 120, 40);

        updateBtn.setBackground(new java.awt.Color(153, 255, 153));
        updateBtn.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        updateBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/icons8_Return_Purchase_26px.png"))); // NOI18N
        updateBtn.setText("UPDATE");
        updateBtn.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 51, 51), 2));
        updateBtn.setContentAreaFilled(false);
        updateBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateBtnActionPerformed(evt);
            }
        });
        jPanel1.add(updateBtn);
        updateBtn.setBounds(490, 410, 140, 40);

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jPanel5);
        jPanel5.setBounds(500, 140, 250, 2);

        deleteBtn.setBackground(new java.awt.Color(153, 0, 0));
        deleteBtn.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        deleteBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/red-x-mark-transparent-background-3.png"))); // NOI18N
        deleteBtn.setText("DELETE");
        deleteBtn.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(153, 0, 0), 2, true));
        deleteBtn.setContentAreaFilled(false);
        deleteBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBtnActionPerformed(evt);
            }
        });
        jPanel1.add(deleteBtn);
        deleteBtn.setBounds(640, 410, 130, 40);
        jPanel1.add(jPanel2);
        jPanel2.setBounds(140, 10, 190, 0);

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jPanel3);
        jPanel3.setBounds(500, 200, 250, 2);

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.add(jPanel6);
        jPanel6.setBounds(500, 260, 250, 2);

        studentList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Student ID", "First Name", "Last Name", "Course Name", "Branch Name"
            }
        ));
        studentList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                studentListMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(studentList);

        jPanel1.add(jScrollPane2);
        jScrollPane2.setBounds(70, 510, 890, 120);

        jPanel4.setBackground(new java.awt.Color(233, 246, 250));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel7.setBackground(new java.awt.Color(0, 153, 153));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("MANAGE STUDENT");
        jPanel7.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 250, 22));

        jPanel4.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 10, 530, 50));

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Yu Gothic UI Semilight", 1, 18)); // NOI18N
        jLabel6.setText("Student ID     :");
        jPanel4.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 80, -1, -1));

        jPanel1.add(jPanel4);
        jPanel4.setBounds(300, 40, 510, 440);

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Student ID     :");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(340, 110, 131, 22);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1095, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void firstNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_firstNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_firstNameFieldActionPerformed

    private void lastNameFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lastNameFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lastNameFieldActionPerformed

    private void courseComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_courseComboActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_courseComboActionPerformed

    private void addBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addBtnActionPerformed
//        String studentID = studentIDField.getText();
//        String firstName = firstNameField.getText();
//        String lastName = lastNameField.getText();
//        String courseName = (String) courseCombo.getSelectedItem();
//
//        String branchName = (String) branchCombo.getSelectedItem();
        try {
            con = ConnectionProvider.getCon();
            stmt = con.createStatement();
            stmt.executeUpdate("insert into student values('" + studentIDField.getText() + "','" + firstNameField.getText() + "','" + lastNameField.getText() + "','" + (String) courseCombo.getSelectedItem() + "','" + (String) branchCombo.getSelectedItem() + "')");
            JOptionPane.showMessageDialog(null, "Successfully Updated!");
            setVisible(false);
            new Student().setVisible(true);
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Student ID Already Exist!");
            setVisible(false);
            new Dashboard().setVisible(true);

            new Student().setVisible(true);
        }
    }//GEN-LAST:event_addBtnActionPerformed

    private void cancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelActionPerformed
        setVisible(false);
        new Dashboard().setVisible(true);
        new Student().setVisible(true);
    }//GEN-LAST:event_cancelActionPerformed

    private void studentIDFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_studentIDFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_studentIDFieldActionPerformed

    private void updateBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateBtnActionPerformed

        try {
              
            con = ConnectionProvider.getCon();
            stmt = con.createStatement();
            String sql = "UPDATE student SET firstName='" + this.firstNameField.getText() + "', lastName='" + this.lastNameField.getText() + "',courseName='" + this.courseCombo.getSelectedItem().toString() + "',branchName='" +  this.branchCombo.getSelectedItem().toString()  + "' WHERE studentID='" + studentIDField.getText() + "'";
            stmt.executeUpdate(sql);

            JOptionPane.showMessageDialog(null, "Data Successfully Updated!");
//            new Statistics().setVisible(true);
//            this.setVisible(false);
            fetch_data();

        } catch (HeadlessException | SQLException e) {
            System.out.println(e.getMessage());
        } finally {
            try {
                stmt.close();
                con.close();
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_updateBtnActionPerformed

    private void deleteBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_deleteBtnActionPerformed

    private void studentListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_studentListMouseClicked
        addBtn.setVisible(false);
        String studentId;
        String firstName;
        String lastName;
        String courseName;
        String branchName;
        int row = studentList.getSelectedRow();
        studentId = (studentList.getModel().getValueAt(row, 0).toString());
        firstName = (studentList.getModel().getValueAt(row, 1).toString());
        lastName = (studentList.getModel().getValueAt(row, 2).toString());
        courseName = (studentList.getModel().getValueAt(row, 3).toString());
        branchName = (studentList.getModel().getValueAt(row, 4).toString());

        studentIDField.setText(studentId);
        firstNameField.setText(firstName);
        lastNameField.setText(lastName);
        courseCombo.setSelectedItem(courseName);
        branchCombo.setSelectedItem(branchName);
    }//GEN-LAST:event_studentListMouseClicked

  
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Student().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addBtn;
    private javax.swing.JComboBox<String> branchCombo;
    private javax.swing.JButton cancel;
    private javax.swing.JComboBox<String> courseCombo;
    private javax.swing.JButton deleteBtn;
    private javax.swing.JTextField firstNameField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField lastNameField;
    private javax.swing.JTextField studentIDField;
    private rojerusan.RSTableMetro studentList;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
